### ISSUE TITLE
Default clone step: GIN-specific docker container with script

### ISSUE THREAD

**Issue by achilleas-k** [G-Node/gin-proc#11]
Since we need to override the default clone step to clone via SSH and download annexed data, the clone step should be handled by a container that performs all the necessary steps.  We could host this on dockerhub and make it GIN specific.  Ideally, the clone step in the drone.yml configuration for all repositories should be as follows:

```yaml
- name: clone
  image: docker:gnode/gin-proc-clone
  environment:
    SSH_KEY:
      from_secret: DRONE_PRIVATE_SSH_KEY
```

The container will be built with git and git-annex and the entrypoint should be a script that uses the [default drone environment](https://docs.drone.io/reference/environ/) to clone the repository (e.g., `git clone $DRONE_REMOTE_URL` for the initial clone step).

The gin-proc web service could also add extra fields for specifying which annexed file content to download (if not everything).
